config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :sessions
  resources :posts do
    resources :comments do
      post 'publish', to: 'comments#publish', as: 'publish'
    end
  end
  # resources :comment_votes, only: %i[create update destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  # post 'posts/:id/comments/:id/publish', to: 'comments#publish', as: 'publish'

  post 'comment_vote', to: 'comment_votes#vote'
  post 'posts/:id', to: 'posts#show'
  get 'search', to: 'posts#search'
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author
  belongs_to :post, counter_cache: true
  has_many :comment_votes, dependent: :destroy

  validates :body, presence: true

  enum status: %i[unpublished published]

  scope :published, -> { where(status: :published) }
  scope :unpublished, -> { where(status: :unpublished) }

  def edited?
    self.created_at != self.updated_at
  end

  has_ancestry

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[ edit create update ]
  before_action :set_comment, only: %i[ edit update destroy ]
  before_action :authorize, only: %i[ create edit destroy ]
  before_action :access_denied, only: %i[ destroy edit update ]

  def index
    redirect_to Post.find(params[:post_id])
  end

  def edit
    redirect_to @post, alert: "Comment can't be edited" if deny_edit(@comment)
  end

  def create
    @comment = @post.comments.new(comment_params.merge(author: current_author))
    respond_to do |format|
      if @comment.save
        @comment.update_column(:status, :published) if @comment.has_parent?
        format.js { flash.notice = 'Comment was successfully created.' }
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
      else
        format.html { render 'posts/show', status: :unprocessable_entity }
      end
    end
  end

  def publish
    @comment = Comment.find(params[:comment_id])
    @comment.update_column(:status, :published)
    redirect_to @comment.post
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_url(@comment.post), notice: "Comment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id, :author_id, :parent_id, :parent)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def access_denied
    redirect_to @post, alert: 'Not your comment' unless current_author == @comment.author
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-block" id="comment-<%= comment.id %>">
  <div class="d-flex justify-content-start align-items-center">
    <div class="author-name d-inline-flex align-self-stretch">
      <%= "#{comment.author.first_name}:" %>
      <%= image_tag(comment.author.avatar, class: 'sm-avatar', alt: '<avatar>') %>
    </div>
    <div class="comment-body d-inline-flex flex-grow-1">
      <%= simple_format(comment.body) %>
    </div>
    <% if comment.published? %>
      <%= render 'comment_votes/votes', comment: comment %>
    <% else %>
      <%= link_to "Publish", post_comment_publish_path(comment.post, comment), method: :post %>
    <% end %>
  </div>
  <% if comment.edited? %>
    <div class="">
        <b>EDITED</b>
    </div>
  <% end %>
  <%= link_to 'Edit', edit_post_comment_path(@post, comment) unless deny_edit(comment) %>
  <%= link_to 'Destroy', [@post, comment], method: :delete, data: { confirm: 'Are you sure?' }, remote: true if current_author == comment.author %>
  <a href="#" class="comment-form-display">reply</a>
  <div class="sub-comment-form">
    <%= render 'comments/form', parent: comment %>
  </div>
  <div class="sub-comment">
    <%= render comment.children %>
  </div>
</div>

<script>
  document.querySelectorAll('.comment-form-display').forEach((el) => {
    el.addEventListener('click', (ev) => {
      ev.preventDefault();
      el.nextElementSibling.style = 'display: block;';
    })
  })
</script>

app/views/comments/_form.html.erb
<% comment = @post.comments.build %>
<%= form_with(model: [@post, comment], local: false) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area(:body, class: 'form-control') %>
  </div>
    <% if !parent.nil? %>
      <%= form.hidden_field :parent_id, value: "#{parent.id}" %>
    <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");
$('#notice').append("<p><%= j "#{notice}" %></p>");
<% notice.clear %>

app/views/comments/destroy.js.erb
document.querySelector('#comment-<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<%= params %>