config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :sessions
  resources :posts do
    resources :comments do
      post 'publish', to: 'comments#publish', as: 'publish'
    end
  end
  # resources :comment_votes, only: %i[create update destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  # post 'posts/:id/comments/:id/publish', to: 'comments#publish', as: 'publish'

  post 'comment_vote', to: 'comment_votes#vote'
  post 'posts/:id', to: 'posts#show'
  get 'search', to: 'posts#search'
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


end

app/models/author.rb
class Author < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :comment_votes, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w\-\.]+@\w+\.\w+\z/i
  VALID_PASSWORD_REGEX = /\A[A-Za-z0-9\-\+_]{8,20}\z/

  validates :email, :first_name, :last_name, :gender, :birthday, presence: true
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, format: { with: VALID_PASSWORD_REGEX }, allow_nil: true

  before_save :downcase_email

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  private
  def downcase_email
    self.email.downcase!
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]
  before_action :access_denied, only: %i[ destroy edit update ]
  before_action :set_visits, only: %i[ show ]

  def new
    @author = Author.new
  end

  def show
  end

  def edit
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      session[:author_id] = @author_id
      redirect_to root_url, notice: 'Thank you for signing up'
    else
      render 'new'
    end
  end

  def destroy
  end

  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Changes accepted" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def author_params
    params.require(:author).permit(:email, :password, :password_confirmation, :first_name, :last_name, :gender, :birthday, :avatar)
  end

  def set_author
    @author = Author.find(params[:id])
  end

  def access_denied
    redirect_to @author, alert: 'Access denied' unless current_author == @author
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<%= form_with(model: @author) do |f| %>
  <% if @author.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :first_name %><br/>
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :last_name %><br/>
  <%= f.text_field :last_name %>
</div>
<div class="field">
  <%= f.label :birthday %><br/>
  <%= f.text_field :birthday %>
</div>
<div class="field">
  <%= f.label :gender %><br/>
  <%= f.text_field :gender %>
</div>
<div class="field">
  <%= f.label :avatar %><br/>
  <%= f.text_field :avatar %>
</div>
<div class="actions"><%= f.submit "Save changes" %></div>
<% end %>

app/views/authors/new.html.erb
<h1>Sign Up</h1>

<%= form_for @author do |f| %>
  <% if @author.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br/>
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :gender %><br/>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br/>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<div class="container">
<%= image_tag(@author.avatar, class: 'avatar', style: "max-height: 300px; max-width: 300px") %><br><br>

  <table class="table table-hover table-bordered table-striped col-4">
    <tr>
      <td>First Name</td>
      <td><%= @author.first_name %></td>
    </tr>
    <tr>
      <td>Last Name</td>
      <td><%= @author.last_name %></td>
    </tr>
    <tr>
      <td>Gender</td>
      <td><%= @author.gender %></td>
    </tr>
    <tr>
      <td>Birthday</td>
      <td><%= @author.birthday %></td>
    </tr>
  </table>
</div>


<%= link_to 'Edit', edit_author_path if current_author == @author %>

<%= render 'sessions/modal' if render_modal? %>