config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :sessions
  resources :posts do
    resources :comments do
      post 'publish', to: 'comments#publish', as: 'publish'
    end
  end
  # resources :comment_votes, only: %i[create update destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  # post 'posts/:id/comments/:id/publish', to: 'comments#publish', as: 'publish'

  post 'comment_vote', to: 'comment_votes#vote'
  post 'posts/:id', to: 'posts#show'
  get 'search', to: 'posts#search'
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="/css/main.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-success bg-opacity-50">
    <header>
      <%= link_to 'Main', posts_path %>
      <%= link_to 'My page', author_path(current_author) if current_author %>
      <br>

      <% if current_author %>
        Logged in as <%= current_author.email %>.
        <%= image_tag(current_author.avatar, class: 'sm-avatar', alt: '<avatar>') if current_author.avatar %>
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>

      <%= form_tag search_path, method: :get do %>
        <div class="">
          <%= search_field_tag :search %>
        </div>
        <div class="actions"><%= submit_tag "Search" %></div>
      <% end %>
    </header>
    <br>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>